### ISSUE TITLE
"Identifier 'makeErrorCause' has already been declared" error when building

### ISSUE THREAD

**Issue by savissimo** [mdbassit/Coloris#47]
I tried to build Coloris from source, but after doing `yarn install` and `yarn build` I got this syntax error:

```
SyntaxError: D:\ss\varisw\Coloris\.yarn\cache\make-error-cause-npm-1.2.2-a8184cb0ea-04c3534363.zip\node_modules\make-error-cause\dist\index.js: Identifier 'makeErrorCause' has already been declared. (12:4)

  10 |     return makeError(value, _super);
  11 | }
> 12 | var makeErrorCause;
     |     ^
  13 | (function (makeErrorCause) {
  14 |     var BaseError = (function (_super) {
  15 |         __extends(BaseError, _super);
    at instantiate (D:\ss\varisw\Coloris\.yarn\cache\@babel-parser-npm-7.18.0-77a18bef7b-253b5828bf.zip\node_modules\@babel\parser\src\parse-error\credentials.js:61:22)
    at toParseError (D:\ss\varisw\Coloris\.yarn\cache\@babel-parser-npm-7.18.0-77a18bef7b-253b5828bf.zip\node_modules\@babel\parser\src\parse-error.js:58:12)
    at Parser.raise (D:\ss\varisw\Coloris\.yarn\cache\@babel-parser-npm-7.18.0-77a18bef7b-253b5828bf.zip\node_modules\@babel\parser\src\tokenizer\index.js:1736:19)
    at ScopeHandler.checkRedeclarationInScope (D:\ss\varisw\Coloris\.yarn\cache\@babel-parser-npm-7.18.0-77a18bef7b-253b5828bf.zip\node_modules\@babel\parser\src\util\scope.js:153:19)
    at ScopeHandler.declareName (D:\ss\varisw\Coloris\.yarn\cache\@babel-parser-npm-7.18.0-77a18bef7b-253b5828bf.zip\node_modules\@babel\parser\src\util\scope.js:128:14)
    at Parser.declareNameFromIdentifier (D:\ss\varisw\Coloris\.yarn\cache\@babel-parser-npm-7.18.0-77a18bef7b-253b5828bf.zip\node_modules\@babel\parser\src\parser\lval.js:707:16)
    at Parser.checkIdentifier (D:\ss\varisw\Coloris\.yarn\cache\@babel-parser-npm-7.18.0-77a18bef7b-253b5828bf.zip\node_modules\@babel\parser\src\parser\lval.js:702:12)
    at Parser.checkLVal (D:\ss\varisw\Coloris\.yarn\cache\@babel-parser-npm-7.18.0-77a18bef7b-253b5828bf.zip\node_modules\@babel\parser\src\parser\lval.js:605:12)
    at Parser.parseVarId (D:\ss\varisw\Coloris\.yarn\cache\@babel-parser-npm-7.18.0-77a18bef7b-253b5828bf.zip\node_modules\@babel\parser\src\parser\statement.js:1254:10)
    at Parser.parseVar (D:\ss\varisw\Coloris\.yarn\cache\@babel-parser-npm-7.18.0-77a18bef7b-253b5828bf.zip\node_modules\@babel\parser\src\parser\statement.js:1220:12) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'VarRedeclaration',
  loc: Position { line: 12, column: 4, index: 461 },
  pos: [Getter/Setter]
}
```

Any clues?

**Comment by melloware** [comment]
I don't know anything about `yarn` but it seems to work fine with `npm`.

**Comment by savissimo** [comment]
I managed to build with `npm`.
